name: Build & Deploy

on:
  push:
    tags:
      - 'v*-prod*'
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

permissions:
  contents: write

jobs:
  build-ui:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install NX
        uses: nrwl/nx-set-shas@v2

      - name: Cache Deps
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-qa-build-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Format
        run: yarn nx format:check --all --verbose

      - name: Lint
        run: yarn nx run-many --target=lint --all --skip-nx-cache

      - name: Tests
        run: yarn nx run-many --target=test --all --skip-nx-cache

      - name: Build
        run: yarn nx run-many --target=build --all --configuration=qa --skip-nx-cache

      - name: Deploy on GH-PAGES
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
